@url_dev=http://localhost:3055/v1/api

### signup
### Update postman
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop HocPV",
    "email": "hocpv2@vanhocpham.com",
    "password": "abc123"
}